import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"O_P_Chatgpt_bot") 
SUDO=os.environ.get("SUDO","5371786986")
BOT_NAME = os.environ.get("BOT_NAME","𝙾𝙿 𝙷𝙰𝙲𝙺𝙴𝚁 CHATGPT BOT")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/d106519f324f3309b23eb.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","mr_sukkun")
# OWNER_USERNAME = os.environ.get("OWNER_USERNAME","Legend_of_all_groups")
SUDO=os.environ.get("SUDO","5371786986")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","the_support_chat")
